name: Genearate BBE files on demand

<<<<<<< HEAD
on: 
=======
on:
>>>>>>> 88d08232dd50c54f4748de0b2f7e7626f3adf094
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
<<<<<<< HEAD
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      env:
        GOPATH: /home/runner/work/ballerina-release
    
    - name: Install Go module blackfriday
      run: go get github.com/russross/blackfriday

    - name: Install jq for json manipulation
      run: sudo apt-get install jq

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Clone ballerina-release
      run: git clone -b upstream-master https://$GITHUB_TOKEN@github.com/Ballerina-By-Examples/ballerina-release.git

    - name: Clone ballerina-distribution
      run: |
        git clone -b upstream-master https://$GITHUB_TOKEN@github.com/Ballerina-By-Examples/ballerina-distribution.git

    - name: Generate BBEs
      run: |
        cd ballerina-release
        cp ../ballerina-distribution/examples/index.json ../_data/all-bbes.json
        cp -r ../ballerina-distribution/examples .

        go run ballerinaByExample/tools/generate.go "examples" "swan-lake" "by-example" "true" "true" "true"

    - name: Archive BBE HTML files
      uses: actions/upload-artifact@v3.1.0
      with:
        name: bbe-files
        path: ballerina-release/by-example
=======
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        env:
          GOPATH: /home/runner/work/ballerina-release

      - name: Install Go module blackfriday
        run: go get github.com/russross/blackfriday

      - name: Install jq for json manipulation
        run: sudo apt-get install jq

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Clone ballerina-release
        run: git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-release.git

      - name: Clone ballerina-distribution
        run: |
          git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-distribution.git
          cd ballerina-distribution
          git checkout -b 2201.0.x origin/2201.0.x
          cd ..

      - name: Generate BBEs
        run: |
          cd ballerina-release
          cp ../ballerina-distribution/examples/index.json ../_data/all-bbes.json
          cp -r ../ballerina-distribution/examples .

          go run ballerinaByExample/tools/generate.go "examples" "swan-lake" "by-example" "true" "true" "true"

      - name: Archive BBE HTML files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: bbe-files
          path: ballerina-release/by-example
>>>>>>> 88d08232dd50c54f4748de0b2f7e7626f3adf094
