name: Create a PR for Swan Lake BBE pages on Ballerina distribution repo changes

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
      NGROK_TOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: bbe-generation-v2

      - name: Run container
        run: docker-compose up -d

      - uses: vmactions/ngrok-tunnel@v0.0.1
        with:
          protocol: http
          port: 4000
