name: Create a PR for Swan Lake BBE pages on Ballerina distribution repo changes

on:
  repository_dispatch:
  workflow_dispatch:
  push:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: bbe-generation-v2

      - name: Run container
        run: docker-compose up -d

      - name: Install ngrok and host the website
        run: |
          sudo snap install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
          ngrok http 4000
