name: Create a PR for Swan Lake BBE pages on Ballerina distribution repo changes

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: upstream-dev

      - name: Install dependencies
        run: npm i

      - name: Clone ballerina-distribution repository
        run: git clone https://$GITHUB_TOKEN@github.com/Ballerina-By-Examples/ballerina-distribution.git

      - name: Copy examples to dev website repo
        run: cp -r ./ballerina-distribution/examples .

      - name: Delete already existing BBE HTML files
        run: find ./learn/by-example -type f \( -name "*.html" ! -name "404.html" ! -name "index.html" \) -delete

      - name: Run markdown to HTML generation script
        run: node ./js/markdownConverter.js ./examples ./learn/by-example

      - name: Format code using prettier
        run: npx prettier ./learn/by-example/*.html --write

      - name: Run container
        run: docker-compose up -d

      - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
        with:
          timeout: 1h
          port: 4000
          ngrok_authtoken: ${{ secrets.WEBSITE_TOKEN }}